#!/bin/sh
exec 2>&1
APP_USER="hermes"
HOME="/home/${APP_USER}"
export HOME
HERMES_WRITE_SAFE_ROOT="${HOME}/.hermes"
export HERMES_WRITE_SAFE_ROOT
exec s6-setuidgid hermes /opt/hermes/.venv/bin/hermes gateway run
